#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-SQL-Translator
version:      1.00
version_from: 
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
